CREATE TABLE IF NOT EXISTS CLIENT(
    ID   IDENTITY PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS ACCOUNT(
    ID        IDENTITY    PRIMARY KEY,
    CLIENT_ID BIGINT      NOT NULL,
    NUMBER    VARCHAR(20) NOT NULL UNIQUE,

    FOREIGN KEY (CLIENT_ID) REFERENCES CLIENT (ID)
);

CREATE INDEX FK_CLIENT_IN ON ACCOUNT(CLIENT_ID);

CREATE TABLE IF NOT EXISTS CARD(
    ID         IDENTITY    PRIMARY KEY,
    ACCOUNT_ID BIGINT      NOT NULL,
    NUMBER     VARCHAR(20) NOT NULL UNIQUE,
    BALANCE    DECIMAL     NOT NULL,

    FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT (ID)
);

CREATE INDEX FK_ACCOUNT_ID ON CARD(ACCOUNT_ID);