CREATE TABLE IF NOT EXISTS client(
    id IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS account(
    id IDENTITY PRIMARY KEY,
    client_id BIGINT NOT NULL,
    number VARCHAR(20) NOT NULL UNIQUE,
    FOREIGN KEY (client_id) REFERENCES client (id)
);

CREATE TABLE IF NOT EXISTS card(
    id IDENTITY PRIMARY KEY,
    account_id BIGINT NOT NULL,
    number VARCHAR(20) NOT NULL UNIQUE,
    balance DECIMAL,
    FOREIGN KEY (account_id) REFERENCES account (id)
);