CREATE TABLE IF NOT EXISTS CLIENT(
    ID      IDENTITY     PRIMARY KEY,
    NAME    VARCHAR(255) NOT NULL,
    VERSION BIGINT       DEFAULT 0
);

CREATE TABLE IF NOT EXISTS ACCOUNT(
    ID         IDENTITY    PRIMARY KEY,
    NUMBER     VARCHAR(20) NOT NULL UNIQUE,
    BALANCE    DECIMAL     NOT NULL,
    CLIENT_ID  BIGINT      NOT NULL,
    VERSION    BIGINT      DEFAULT 0,

    FOREIGN KEY (CLIENT_ID) REFERENCES CLIENT (ID)
);

CREATE INDEX FK_CLIENT_IN ON ACCOUNT(CLIENT_ID);

CREATE TABLE IF NOT EXISTS CARD(
    ID          IDENTITY    PRIMARY KEY,
    NUMBER      VARCHAR(20) NOT NULL UNIQUE,
    ACCOUNT_ID  BIGINT      NOT NULL,
    VERSION     BIGINT      DEFAULT 0,

    FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT (ID)
);

CREATE INDEX FK_ACCOUNT_ID ON CARD(ACCOUNT_ID);